### ISSUE TITLE
angr 8 release tracker

### ISSUE THREAD

**Issue by ltfish** [angr/angr#1209]
We are almost ready to embrace the future and make angr Python 3 compatible. Doing so means ticking angr version number from 7 to 8, migrating a bunch of modules and projects, and (unfortunately) dropping support for Python 2. We are sure that Python 3 is the future, and the sooner we finish migration, the sooner we can start working on more important and exciting features.

Here is a complete todo list for the angr 8 release.

All involved projects: angr, claripy, CLE, PyVEX, archinfo, Patcherex, fidget, fuzzer, colorguard, angrop, tracer, angr-doc, angr-platforms, angr-management, ailment, and angr-dev.

- [x] Rename `CFGAccurate` to `CFGEmulated`.
- [x] Merge in @subwire 's ARM CFG fixes to `py3k` branches of PyVEX.
- [x] Merge in @subwire 's ARM CFG fixes to `py3k` branches of angr.
- [x] Are there any more compatibility-breaking changes? Now it's a great time to implement them :)
- [x] For each involved project, make sure all recent PRs and pushes to the `master` branch are included in the `py3k` branch.
- [x] Move `Patcherex` from `/shellphish` to `/angr` on GitHub. Mark `Shellphish/patcherex` as deprecated/moved.
- [x] For the `py3k` branch of each involved project, make sure all tests pass on Travis CI.
- [x] Update angr's README.md stating that angr is Python 3 compatible. Python 2 is not supported any more.
- [x] Make one last angr 7 release on PyPI. It will be the last angr release that supports Python 2.
- [x] Build and upload angr 7 wheels for angr/pyvex on Linux/Windows 32/64-bit.
- [x] Write a blog post on this migration. Include a link to the angr 8 migration page in angr-docs.
- [x] Update blog post with final angr 7 version number and a `pip freeze` from the final working installation.
- [x] Update angr installation instructions (especially on Windows) in angr-docs.
- [x] Shameless self-promotion? :)
- [x] For each involved project, merge the `py3k` branch into `master`.
- [x] Change release script to use last two digits of year as minor version number.
- [x] Release angr 8 on PyPI.
- [x] Build and upload angr 8 wheels for angr/pyvex on Linux/Windows 32/64-bit.
- [x] Publish blog post.

Feel free to edit this post or comment below to include important TODOs.

**Comment by rhelmot** [comment]
For the third-last bullet about recent PRs and pushes to master - are we planning to force-push py3k over master? Why shouldn't this just be a normal merge or rebase, depending on the history complexity?

**Comment by ltfish** [comment]
> are we planning to force-push py3k over master?

I think our consensus is that we merge the py3k branches to the five core angr projects. For other projects, we will squash the commits before merging. No force-push is required.

**Comment by rhelmot** [comment]
So why do we have the third-last bullet?

**Comment by ltfish** [comment]
Because commits that only exist in `master` branches may not be Python 3 compatible. Ideally the only difference between a `master` branch and a `py3k` branch are Python-3 related changes.

**Comment by subwire** [comment]
angr-platforms now lints and passes all tests, meaning we're ready to go

Well.... almost ready to go.... 
https://twitter.com/angrdothorse/status/1045166119860887554

**Comment by rhelmot** [comment]
HELLLLLLLLLLLLLLLLL YEAH BABEY

**Comment by ltfish** [comment]
We did it!

**Comment by zardus** [comment]
Mind blown.
