### ISSUE TITLE
Integrate the SAILR deoptimization passes into the decompiler

### ISSUE THREAD

**Issue by mahaloz** [angr/angr#4229]
### Description

Our USENIX 2024 paper, ["Ahoy SAILR! There is No Need to DREAM of C: A Compiler-Aware Structuring Algorithm for Binary Decompilation"](https://www.zionbasque.com/files/publications/sailr_usenix24.pdf), implements many new features for making our decompilation have a better control flow structure according to the [SAILR Evaluation](https://github.com/mahaloz/sailr-eval). The deoptimizations described in the paper were implemented in a fork: [angr-sailr](https://github.com/mahaloz/sailr-eval). 

Many of these changes will need to be done over the next few weeks to ensure their integration into the `master` branch is stable and usable. This issue serves as the big task tracker of the integration. For questions on specific steps, contact @mahaloz. 

## Tasks
- [x] Implement a new type of `Optimization` class for structuring aware optimizations, much like [this](https://github.com/mahaloz/angr-sailr/blob/be3855762a84983137696aa14efe2431a86a7e97/angr/analyses/decompiler/optimization_passes/optimization_pass.py#L241): https://github.com/angr/angr/pull/4250
- [x] Port `EagerReturns` optimization to be goto aware: https://github.com/angr/angr/pull/4250
- [x] Port the `CrossJumpRevert` optimization: https://github.com/angr/angr/pull/4431
- [x] Port the `ConstantDepropataion` optimization: https://github.com/angr/angr/pull/4725
- [x] Port Phoenix fixes for goto tracking: https://github.com/angr/angr/pull/4250
- [x] Enable `SwitchLowerer` optimization by default: https://github.com/angr/angr/pull/4545
- [x] Merge in if-else-swapper: https://github.com/angr/angr/pull/4179
- [x] Fix edge virtualization ordering to be more similar to SAILR (maybe measure this) so more cases work: #4055 
- [X] Port all structuring core testcases from [sailr-eval deoptimization tests](https://github.com/mahaloz/sailr-eval/blob/main/tests/test_deoptimization.py): #4726
- [x] Reimplement `DuplicationReverter` without bad `paths_in_between` check (slow): #4726   

## Optional Tasks
- Integrate [cfgutils](https://github.com/mahaloz/cfgutils) into CI for simple CFGED increase/decrease detection

**Comment by mahaloz** [comment]
And with the close of #4726, that's a wrap! Sorry for the delay to everyone watching :)
